name: "WalletConnect RPC Server"
description: "Boot a WalletConnect RPC Server for Vara"
inputs:
  port:
    description: "Port to host proxy on"
    required: true
    default: 8585
  requested_network:
    description: "Requested network to connect to"
    required: true
    default: vara
runs:
  using: "composite"
  runs-on: ubuntu-latest
  container:
    image: btwiuse/arch:dev
  steps:
    - run: |
        cd ${{ github.action_path }}
        bun install
        LARGE=false RESHOW_DELAY=10000 PORT="${{ inputs.port }}" ./index.mjs &
        while ! nc -z localhost "${{ inputs.port }}"; do
          sleep 0.1
        done
        ufo pub :"${{ inputs.port }}"
      shell: bash
branding:
  icon: "server"
  color: "yellow"
