name: "WalletConnect RPC Server"
description: "Boot a WalletConnect RPC Server for Vara"
inputs:
  port:
    description: "Port to host proxy on"
    required: true
    default: 8585
  requested_network:
    description: "Requested network to connect to"
    required: true
    default: vara
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "server"
  color: "yellow"
