name: "Seacrest WalletConnect Server"
description: "Boot a secure Seacrest WalletConnect Signing Proxy Server"
inputs:
  ethereum_url:
    description: "Ethereum node to proxy requests to"
    required: true
    default: "https://mainnet.infura.io"
  port:
    description: "Port to host proxy on"
    required: true
    default: 8585
  requested_network:
    description: "Requested network to connect to"
    required: true
    default: 1
  wallet_connect_project_id:
    description: "Your WalletConnect project id [defaults to secret WALLET_CONNECT_PROJECT_ID]"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}
        npm install
        LARGE=false RESHOW_DELAY=10000 node src/index.mjs "${{ inputs.requested_network }}" "${{ inputs.wallet_connect_project_id }}" "${{ inputs.ethereum_url }}" "${{ inputs.port }}" &
        while ! nc -z localhost "${{ inputs.port }}"; do
          sleep 0.1
        done
        curl -S -s -i "http://localhost:${{ inputs.port }}" -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}'
      shell: bash
branding:
  icon: 'server'
  color: 'yellow'
