name: Test Local Action

on:
  workflow_dispatch:

jobs:
  check:
    name: Test Local Seacrest Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Seacrest
        uses: ./
        with:
          requested_network: "vara"
